name: orbx
description: OrbX VPN Client with Protocol Mimicry
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.0
  get_it: ^8.2.0

  # GraphQL (for OrbNet API)
  graphql_flutter: ^5.1.2

  # HTTP Client (for OrbX servers)
  dio: ^5.4.0
  http: ^1.1.0
  crypto: ^3.0.3

  # Network
  connectivity_plus: ^6.1.5
  network_info_plus: ^7.0.0

  # WireGuard (Platform-specific)
  # We'll use method channels for this

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase (for FCM notifications)
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0

  # UI Components
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  cached_network_image: ^3.3.1

  # Location & Geolocation
  geolocator: ^14.0.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.3.3
  logger: ^2.0.2
  equatable: ^2.0.5

  # Charts (for statistics)
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
