// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZmLJ7UZYwqgKfSDAdq-ZDVlBzCcDvFw',
    appId: '1:215771191022:web:a4f1c29ea49a2356b005ff',
    messagingSenderId: '215771191022',
    projectId: 'ndb-inc---ga4',
    authDomain: 'ndb-inc---ga4.firebaseapp.com',
    storageBucket: 'ndb-inc---ga4.firebasestorage.app',
    measurementId: 'G-N02BJWPQR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXukekHvKzvZ3kkXKmXoc1EUA1OnMy2LI',
    appId: '1:215771191022:android:6cd77ee3a2a3d2d4b005ff',
    messagingSenderId: '215771191022',
    projectId: 'ndb-inc---ga4',
    storageBucket: 'ndb-inc---ga4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWnapBg5KN_Sy7Kn5IlywlpF6p1Cc3VBg',
    appId: '1:215771191022:ios:bc9cca3e27a872abb005ff',
    messagingSenderId: '215771191022',
    projectId: 'ndb-inc---ga4',
    storageBucket: 'ndb-inc---ga4.firebasestorage.app',
    iosBundleId: 'com.example.orbx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWnapBg5KN_Sy7Kn5IlywlpF6p1Cc3VBg',
    appId: '1:215771191022:ios:bc9cca3e27a872abb005ff',
    messagingSenderId: '215771191022',
    projectId: 'ndb-inc---ga4',
    storageBucket: 'ndb-inc---ga4.firebasestorage.app',
    iosBundleId: 'com.example.orbx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiZmLJ7UZYwqgKfSDAdq-ZDVlBzCcDvFw',
    appId: '1:215771191022:web:71295fce9da5e2f6b005ff',
    messagingSenderId: '215771191022',
    projectId: 'ndb-inc---ga4',
    authDomain: 'ndb-inc---ga4.firebaseapp.com',
    storageBucket: 'ndb-inc---ga4.firebasestorage.app',
    measurementId: 'G-8YL1LV7BJP',
  );
}
